[project]
name = "introvert"  # Changed to lowercase for consistency
version = "0.1.0"
description = "Advanced Personality Classification with ML ensemble methods"
authors = [
    {name = "Jeremy Vachier", email = "your.email@example.com"}
]
readme = "README.md"
requires-python = ">=3.11,<3.13"

dependencies = [
    # Core ML libraries
    "numpy>=1.24.0",
    "pandas>=2.0.0",
    "scikit-learn>=1.3.0,<1.4.0",
    # Advanced ML models
    "catboost>=1.2.0",
    "lightgbm>=4.0.0",
    "xgboost>=2.0.0",
    # Deep learning and neural networks
    "torch>=2.0.0",
    "pytorch-tabnet>=4.1.0",
    # Feature engineering and preprocessing
    "category-encoders>=2.6.0",
    "imbalanced-learn>=0.11.0",
    "scipy>=1.11.0",
    # Hyperparameter optimization
    "optuna>=3.4.0",
    # Plotting and visualization
    "matplotlib>=3.6.0",
    "seaborn>=0.11.0",
    # Progress bars and utilities
    "tqdm>=4.65.0",
    "typing-extensions>=4.7.0",
    "sdv>=1.24.0",
]

[project.optional-dependencies]
automl = [
    "autogluon>=1.1.1",
    "h2o>=3.44.0",
]
dev = [
    "jupyter>=1.0.0",
    "notebook>=7.0.0",
    "ipython>=8.12.0",
    "ipykernel>=6.25.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

# Tell hatchling to include all Python files
[tool.hatch.build.targets.wheel]
include = [
    "*.py",
    "*.ipynb",
    "README.md",
]

[tool.uv]
dev-dependencies = [
    "jupyter>=1.0.0",
    "notebook>=7.0.0",
    "ipython>=8.12.0",
    "ipykernel>=6.25.0",
]
