version: '3.8'

services:
  personality-dash:
    build:
      context: ..
      dockerfile: dash_app/Dockerfile
    ports:
      - "8050:8050"
    environment:
      - MODEL_NAME=personality_model
      - MODEL_STAGE=Production
      - DEBUG=false
    volumes:
      - mlflow_data:/app/mlruns
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8050/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

  # Optional: MLflow tracking server
  mlflow:
    image: mlflow/mlflow:latest
    ports:
      - "5000:5000"
    command: >
      mlflow server
      --host 0.0.0.0
      --port 5000
      --default-artifact-root /mlflow/artifacts
      --backend-store-uri sqlite:///mlflow/mlflow.db
    volumes:
      - mlflow_data:/mlflow
    restart: unless-stopped

volumes:
  mlflow_data:
