version: '3.8'

services:
  personality-dash:
    build:
      context: ..
      dockerfile: dash_app/Dockerfile
    ports:
      - "8050:8050"
    environment:
      - MODEL_NAME=ensemble
      - MODEL_STAGE=Production
      - DEBUG=false
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8050/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
