name: Tests

on:
  push:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'dash_app/**'
      - 'tests/**'
      - 'scripts/**'
      - 'pyproject.toml'
      - 'uv.lock'
      - '.github/workflows/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'dash_app/**'
      - 'tests/**'
      - 'scripts/**'
      - 'pyproject.toml'
      - 'uv.lock'
      - '.github/workflows/**'

env:
  UV_SYSTEM_PYTHON: 1

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        version: "latest"

    - name: Install dependencies
      run: |
        uv sync --all-extras

    - name: Run tests
      run: |
        uv run pytest tests/ -v --tb=short

    - name: Check code style with ruff
      run: |
        uv run ruff check .
        uv run ruff format --check .

    - name: Type check with mypy
      run: |
        uv run mypy src/ --ignore-missing-imports
      continue-on-error: true

    - name: Security check with bandit
      run: |
        uv run bandit -r src/ -f json
      continue-on-error: true
